name: Docker Image CI (main push)

on:
  workflow_dispatch:
    inputs:
      runner:
        required: false
        default: ubuntu-latest
        description: The runner of the workflow
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ github.event_name == 'workflow_dispatch' && inputs.runner || 'ubuntu-latest' }}

    steps:
    - uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag fuzzystatic/nitrox-server:latest

    - name: Push the Docker image
      run: docker push fuzzystatic/nitrox-server:latest
